### ISSUE TITLE
Minimum Viable Engine Prototype

### ISSUE THREAD

**Issue by Longor1996** [Longor1996/TCGE#5]
All items listed here are the minimum required, to force implementation of all major systems and their respective subsystems. *Forgetting an item may cause irreparable architectural errors.*

**GUI:**
- [ ] Main-Menu
- [ ] World Management (create/play/delete)
- [ ] Options / Settings
- [ ] Ingame HUD

**Items:**
- [ ] `core:items/wrench`: Changes block properties. (Test property mutation)
- [ ] `core:items/spaxel`: Can mine all block-types. (Test mining system)
- [ ] `core:items/vbrush`: Sculpt blocks & terrain. (Test performance)

**Blocks:**
- [ ] `core:blocks/fluid/air`: Most basic fluid.
- [ ] `core:blocks/fluid/void`: Most basic fluid.
- [ ] `core:blocks/fluid/water`: Most basic fluid.
- [ ] `core:blocks/bedrock`: Unbreakable opaque world boundary block.
- [ ] `core:blocks/barrier`: Unbreakable invisible boundary block.
- [ ] `core:blocks/trigger`: Triggers things if touched by actors.
- [ ] `core:blocks/command`: Executes a command when triggered.

**Actors:**
- [ ] `core:actors/box`: A axis-aligned box.
- [ ] `core:actors/point`: A point.
- [ ] `core:actors/block`: A block as movable actor.
- [ ] `core:actors/items`: A stack of items as actor.
